{
  config,
  lib,
  machine,
  pkgs,
  ...
}:

let
  # Nix timestamps are fixed: same-size edits can otherwise reuse stale Lua.
  clearLuaCache = ''
    nvim_lua_cache=${lib.escapeShellArg "${config.xdg.cacheHome}/nvim/luac"}
    if [ -d "$nvim_lua_cache" ]; then
      ${pkgs.findutils}/bin/find "$nvim_lua_cache" -maxdepth 1 -type f -name '*.luac' -delete
    fi
  '';
in
{
  home.packages = with pkgs; [
    neovim
    tree-sitter
    rust-analyzer
    nil
    nixfmt
    statix
    marksman
    markdownlint-cli2
    markdown-toc
    prettier
  ];

  xdg.configFile."nvim" = {
    source = ../../configs/nvim;
    recursive = true;
    onChange = clearLuaCache;
  };

  xdg.configFile."nvim/lua/plugins/nix-dependencies.lua".onChange = clearLuaCache;

  # The deployed config is read-only, so lazy.nvim keeps its lockfile in the
  # dotfiles checkout (see lua/config/lazy.lua); plugin updates can then record it.
  xdg.configFile."nvim/lua/config/machine.lua".text = ''
    -- Generated by home-manager/modules/nvim.nix.
    return { lockfile = "${machine.dotfilesDirectory}/configs/nvim/lazy-lock.json" }
  '';

  # LuaJIT's library loader does not search Nix store paths automatically.
  xdg.configFile."nvim/lua/plugins/nix-dependencies.lua".text = ''
    -- lazy.nvim regenerates help tags for every plugin given by `dir` on install
    -- and update. The Nix store is read-only and its plugins ship their tags
    -- already, so that step is skipped for them; otherwise each update fails
    -- with "E152: Cannot open /nix/store/.../doc/tags for writing".
    local ok, tasks = pcall(require, "lazy.manage.task.plugin")
    if ok and tasks.docs and not tasks.docs.skips_nix_store then
      local skip = tasks.docs.skip
      tasks.docs.skip = function(plugin)
        return vim.startswith(plugin.dir or "", "/nix/store/") or skip(plugin)
      end
      tasks.docs.skips_nix_store = true
    end

    return {
      {
        "mrcjkb/rustaceanvim",
        opts = { server = { cmd = { "${pkgs.rust-analyzer}/bin/rust-analyzer" } } },
      },
      -- Keep language tools and browser preview reproducible through Nix.
      {
        "neovim/nvim-lspconfig",
        opts = { servers = { nil_ls = { mason = false }, marksman = { mason = false } } },
      },
      {
        "mason-org/mason.nvim",
        opts = function(_, opts)
          local provided = { ["markdownlint-cli2"] = true, ["markdown-toc"] = true, prettier = true }
          opts.ensure_installed = vim.tbl_filter(function(tool) return not provided[tool] end, opts.ensure_installed or {})
        end,
      },
      {
        "iamcco/markdown-preview.nvim",
        dir = "${pkgs.vimPlugins.markdown-preview-nvim}",
        build = false,
      },
      {
        "MeanderingProgrammer/render-markdown.nvim",
        dir = "${pkgs.vimPlugins.render-markdown-nvim}",
      },
      {
        "folke/snacks.nvim",
        opts = {
          picker = {
            db = { sqlite3_path = "${pkgs.sqlite.out}/lib/libsqlite3.so" },
          },
        },
      },
    }
  '';
}
