[Autologin]
Relogin=false
Session=plasma
User=

[General]
HaltCommand=/usr/bin/systemctl poweroff
Numlock=on
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=silent

[Users]
MaximumUid=29999
MinimumUid=1000
