#!/usr/bin/env python3
"""Import tested Myfish functions, preserving explicit workstation overrides."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'home-manager/scripts'))
from github_checks import api, check_runs, eligible, revision

LOCK = Path('configs/fish/shared-source.json')
FUNCTIONS = Path('configs/fish/functions')


def filename(name):
    if not isinstance(name, str) or not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_-]*\.fish', name):
        raise ValueError(f'Invalid function filename: {name!r}')
    return name


def digest(data):
    return hashlib.sha256(data).hexdigest()


def read_lock(root):
    lock = json.loads((root / LOCK).read_text())
    if lock['version'] != 1 or lock['repository'] != 'Commanderx-code/Myfish':
        raise ValueError('Unsupported shared Fish source')
    revision(lock['revision'])
    if not isinstance(lock['overrides'], dict) or not isinstance(lock['files'], dict):
        raise ValueError('Invalid shared Fish manifest')
    for name in [*lock['overrides'], *lock['files']]:
        filename(name)
    if set(lock['overrides']) & set(lock['files']):
        raise ValueError('A function cannot be both shared and overridden')
    return lock


def verify(root, lock=None):
    lock = lock or read_lock(root)
    for name, expected in lock['files'].items():
        target = root / FUNCTIONS / name
        if target.is_symlink() or not target.is_file() or digest(target.read_bytes()) != expected:
            raise ValueError(f'Shared file changed: {target}. Edit Myfish, or explicitly declare a workstation override.')
    return lock


def synchronize(root, source, head):
    revision(head)
    lock = verify(root)
    folder = source / 'modules/fish/functions'
    if folder.is_symlink() or not folder.is_dir():
        raise ValueError('Missing regular Myfish function directory')
    sources = sorted(folder.glob('*.fish'))
    if not sources:
        raise ValueError('Refusing to import an empty Fish source')
    files = {}
    for path in sources:
        name = filename(path.name)
        if path.is_symlink() or not path.is_file():
            raise ValueError(f'Not a regular source file: {path}')
        if name in lock['overrides']:
            continue
        target = root / FUNCTIONS / name
        if name not in lock['files'] and (target.exists() or target.is_symlink()):
            raise ValueError(f'New shared function conflicts with local function: {name}')
        header = (f'# Shared from Commanderx-code/Myfish: modules/fish/functions/{name}\n'
                  '# Generated by scripts/sync-myfish.py; edit Myfish instead.\n')
        files[name] = header.encode() + path.read_bytes()
    # Preflight every source, collision, and local digest before writing or removing anything.
    new = dict(lock, revision=head, files={name: digest(data) for name, data in files.items()})
    if new == lock:
        return False
    for name in set(lock['files']) - set(files):
        (root / FUNCTIONS / name).unlink()
    for name, data in files.items():
        target = root / FUNCTIONS / name
        if not target.exists() or target.read_bytes() != data:
            target.write_bytes(data)
    (root / LOCK).write_text(json.dumps(new, indent=2) + '\n')
    return True


def ensure_validation():
    head = revision(api('repos/Commanderx-code/dotfiles/commits/main')['sha'])
    if not check_runs('dotfiles', head):
        subprocess.run(['gh', 'workflow', 'run', 'check.yml', '--repo',
                        'Commanderx-code/dotfiles', '--ref', 'main'], check=True)
        print(f'Dispatched validation for dotfiles main ({head[:12]})')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument('--check', action='store_true', help='verify shared files offline')
    modes.add_argument('--ensure-validation', action='store_true', help='start missing validation after a bot push')
    args = parser.parse_args()
    if args.check:
        verify(ROOT)
        print('Shared Fish files match their import manifest.')
        return
    if args.ensure_validation:
        ensure_validation()
        return
    if subprocess.check_output(['git', 'status', '--porcelain', '--untracked-files=all'], cwd=ROOT):
        raise ValueError('Import requires a clean checkout')
    head = eligible('Myfish')
    changed = False
    if head:
        with tempfile.TemporaryDirectory(prefix='myfish-source-') as directory:
            source = Path(directory)
            subprocess.run(['git', 'init', '-q', str(source)], check=True)
            subprocess.run(['git', '-C', str(source), 'fetch', '--quiet', '--depth=1',
                            'https://github.com/Commanderx-code/Myfish.git', head], check=True)
            subprocess.run(['git', '-C', str(source), 'checkout', '--quiet', '--detach', 'FETCH_HEAD'], check=True)
            changed = synchronize(ROOT, source, head)
        print(f'Myfish {head[:12]}: ' + ('imported' if changed else 'already imported'))
    else:
        print('Waiting for successful Myfish main CI; keeping the current import.')
    if os.environ.get('GITHUB_OUTPUT'):
        with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
            output.write(f'changed={str(changed).lower()}\n')


if __name__ == '__main__':
    main()
