# Shared from Commanderx-code/Myfish: modules/fish/functions/cdi.fish
# Generated by scripts/sync-myfish.py; edit Myfish instead.
function cdi --description 'Fuzzy cd, including hidden and nested directories'
    __commander_pick_directory --hidden --follow --exclude .git
end
