# Shared from Commanderx-code/Myfish: modules/fish/functions/fcd.fish
# Generated by scripts/sync-myfish.py; edit Myfish instead.
function fcd --description 'Fuzzy cd to an immediate, visible subdirectory'
    __commander_pick_directory --max-depth 1 --no-ignore --follow
end
