# Shared from Commanderx-code/Myfish: modules/fish/functions/gcom.fish
# Generated by scripts/sync-myfish.py; edit Myfish instead.
function gcom
    if test (count $argv) -eq 0
        echo "Usage: gcom <message>"
        return 1
    end
    git add .; or return $status
    git commit -m (string join ' ' -- $argv)
end
