function helpme --description "Show Commander shortcuts, tools, and Config Bible commands"
    set -l b (set_color --bold)
    set -l n (set_color normal)
    set -l g (set_color green)
    set -l c (set_color cyan)
    set -l y (set_color yellow)
    set -l m (set_color magenta)

    echo ""
    echo "$b$c Commander Help$n"
    echo "$y────────────────────────────────────────────────────────────$n"

    echo "$b$g📦 Core$n"
    echo "  $cfastfetch$n             → system info"
    echo "  $cstarship$n              → prompt engine"
    echo "  $czoxide$n                → smarter cd (use: $b$czi$n)"
    echo ""

    echo "$b$g🧭 Navigation$n"
    echo "  $c..$n, $c...$n, $c....$n, $c.....$n → up directories"
    echo "  $cbd$n                    → previous directory"
    echo "  $chome$n                  → cd ~"
    echo "  $cfcd$n                   → fuzzy directory picker"
    echo "  $cmkcd <dir>$n            → create directory + cd"
    echo ""

    echo "$b$g📂 Listing (eza)$n"
    echo "  $cls$n                    → icons + dirs first"
    echo "  $cll$n                    → long list"
    echo "  $cla$n                    → long + hidden files"
    echo "  $ctree$n                  → tree view"
    echo "  $clx$n                    → sort by extension"
    echo "  $clk$n                    → sort by size"
    echo "  $clt$n                    → sort by modified time"
    echo "  $cldir$n                  → directories only"
    echo "  $clf$n                    → files only"
    echo "  $clgit$n                  → git-aware listing"
    echo ""

    echo "$b$g🔎 Search / fzf$n"
    echo "  $cCtrl-P$n                → fuzzy open file"
    echo "  $cCtrl-F$n                → ripgrep search → open in Neovim"
    echo "  $cCtrl-H$n                → fuzzy shell history"
    echo "  $c** + Tab$n              → fuzzy path completion"
    echo "  $ch <pattern>$n           → history | grep"
    echo "  $cp <pattern>$n           → ps aux | grep"
    echo ""

    echo "$b$g📚 Config Bible$n"
    echo "  $cconfig-index$n          → search the Config Bible"
    echo "  $cconfig-index <term>$n   → open Bible filtered by term"
    echo "  $cconfig-index --critical$n → show critical pages"
    echo "  $cconfig-index --planned$n  → show planned items"
    echo "  $cconfig-index --recovery$n → recovery-focused search"
    echo "  $cbible-audit$n           → audit docs against configs"
    echo "  $cbible-audit --metadata$n  → check Bible metadata"
    echo "  $cbible-audit --sources$n   → check documented source paths"
    echo "  $cbible-audit --stale$n     → find old verification dates"
    echo ""

    echo "$b$g🏠 Home Manager$n"
    echo "  $chms$n                   → Home Manager switch"
    echo "  $chm-rebuild$n            → safer HM rebuild helper"
    echo "  $cpkg-owner <cmd>$n       → find package owner of command"
    echo "  $cpkg-install <pkg>$n     → decide HM vs system package"
    echo "  $chome-manager news$n     → unread Home Manager news"
    echo ""

    echo "$b$g💾 Backup / Recovery$n"
    echo "  $cbackup-personal$n       → Restic personal-data backup"
    echo "  $cbackup-everything$n     → full workstation backup"
    echo "  $cbackup-system-state$n   → snapshot system configuration"
    echo "  $cbackup-secrets$n        → encrypted SSH/KWallet backup"
    echo "  $crestic-maintenance$n    → Restic retention + maintenance"
    echo "  $crestic-deep-check$n     → deeper Restic verification"
    echo "  $crestore-system$n        → guided system-state restore"
    echo "  $crestore-apps$n          → review / restore applications"
    echo ""

    echo "$b$g🛠 Updates$n"
    echo "  $cupdate$n                → show available repo updates"
    echo "  $cupgrade$n               → pacman + paru + Flatpak"
    echo "  $cfull-upgrade$n          → full system + Topgrade update"
    echo "  $cfull-upgrade-devel$n    → full update + -git/VCS packages"
    echo "  $ctopgrade$n              → run Topgrade directly"
    echo ""

    echo "$b$g🌱 Git$n"
    echo "  $cgcom \"msg\"$n           → git add . + commit"
    echo "  $clazyg \"msg\"$n          → add + commit + push"
    echo "  $cgit status --short$n    → compact repo status"
    echo ""

    echo "$b$g🧰 Utilities$n"
    echo "  $cserve [port]$n          → quick web server (default 8000)"
    echo "  $cdirsize$n               → size of current directory"
    echo "  $cpsg <name>$n            → search running processes"
    echo "  $cwhatismyip$n            → internal + external IP"
    echo "  $cdocker-clean$n          → prune Docker resources"
    echo "  $cextract <file>$n        → extract common archive formats"
    echo ""

    echo "$b$g📝 Neovim$n"
    echo "  $cnvim$n                  → open Neovim"
    echo "  $clazy$n                  → LazyVim plugin manager"
    echo "  $c:Mason$n                → language tooling manager"
    echo "  $c:checkhealth$n          → Neovim diagnostics"
    echo ""

    echo "$y────────────────────────────────────────────────────────────$n"
    echo "$mTips:$n"
    echo "  Search docs:     $b$cconfig-index <topic>$n"
    echo "  Check the Bible: $b$cbible-audit$n"
    echo "  List functions:  $b$cfunctions | sort$n"
    echo "  List aliases:    $b$caliases$n"
    echo ""
end
