function helpme --description "Show Commander shortcuts, tools, and Config Bible commands"
    set -l b (set_color --bold)
    set -l n (set_color normal)
    set -l g (set_color green)
    set -l c (set_color cyan)
    set -l y (set_color yellow)
    set -l m (set_color magenta)

    echo ""
    echo "$b$c Commander Help$n"
    echo "$y────────────────────────────────────────────────────────────$n"

    echo "$b$g📦 Core$n"
    echo "  $c""fastfetch$n             → system info"
    echo "  $c""starship$n              → prompt engine"
    echo "  $c""zoxide$n                → smarter cd (use: $b$c""zi$n)"
    echo ""

    echo "$b$g🧭 Navigation$n"
    echo "  $c..$n, $c...$n, $c....$n, $c.....$n → up directories"
    echo "  $c""bd$n                    → previous directory"
    echo "  $c""home$n                  → cd ~"
    echo "  fcd                     → pick an immediate subdirectory"
    echo "  cdi                     → pick a nested or hidden directory"
    echo "  $c""mkcd <dir>$n            → create directory + cd"
    echo ""

    echo "$b$g📂 Listing (eza)$n"
    echo "  $c""ls$n                    → icons + dirs first"
    echo "  $c""ll$n                    → long list"
    echo "  $c""la$n                    → long + hidden files"
    echo "  $c""tree$n                  → tree view"
    echo "  $c""lx$n                    → sort by extension"
    echo "  $c""lk$n                    → sort by size"
    echo "  $c""lt$n                    → sort by modified time"
    echo "  $c""ldir$n                  → directories only"
    echo "  $c""lf$n                    → files only"
    echo "  $c""lgit$n                  → git-aware listing"
    echo ""

    echo "$b$g🔎 Search / fzf$n"
    echo "  $c""Ctrl-P$n                → fuzzy open file"
    echo "  $c""Ctrl-F$n                → ripgrep search → open in Neovim"
    echo "  $c""Ctrl-H$n                → fuzzy shell history"
    echo "  $c** + Tab$n              → fuzzy path completion"
    echo "  history                 → fuzzy shell history"
    echo "  psg <pattern>           → search running processes"
    echo ""

    echo "$b$g🏠 Home Manager$n"
    echo "  $c""hms$n                   → Home Manager switch"
    echo "  $c""hm-rebuild$n            → safer HM rebuild helper"
    echo "  $c""pkg-owner <cmd>$n       → find package owner of command"
    echo "  $c""pkg-install <pkg>$n     → decide HM vs system package"
    echo "  $c""home-manager news$n     → unread Home Manager news"
    echo ""

    echo "$b$g💾 Backup / Recovery$n"
    echo "  $c""backup-personal$n       → Restic personal-data backup"
    echo "  $c""backup-everything$n     → full workstation backup"
    echo "  $c""backup-system-state$n   → snapshot system configuration"
    echo "  $c""backup-secrets$n        → encrypted SSH/KWallet backup"
    echo "  $c""restic-maintenance$n    → Restic retention + maintenance"
    echo "  $c""restic-deep-check$n     → deeper Restic verification"
    echo "  $c""restore-system$n        → guided system-state restore"
    echo "  $c""restore-apps$n          → review / restore applications"
    echo ""

    echo "$b$g🛠 Updates$n"
    echo "  $c""update$n                → show available repo updates"
    echo "  upgrade                 → Paru (or Pacman) + Flatpak"
    echo "  $c""full-upgrade$n          → full system + Topgrade update"
    echo "  $c""full-upgrade-devel$n    → full update + -git/VCS packages"
    echo "  $c""topgrade$n              → run Topgrade directly"
    echo ""

    echo "$b$g🌱 Git$n"
    echo "  $c""gcom \"msg\"$n           → git add . + commit"
    echo "  $c""lazyg \"msg\"$n          → add + commit + push"
    echo "  $c""git status --short$n    → compact repo status"
    echo ""

    echo "$b$g🧰 Utilities$n"
    echo "  $c""serve [port]$n          → quick web server (default 8000)"
    echo "  $c""dirsize$n               → size of current directory"
    echo "  $c""psg <name>$n            → search running processes"
    echo "  $c""docker-clean$n          → prune Docker resources"
    echo "  $c""extract <file>$n        → extract common archive formats"
    echo ""

    echo "$b$g📝 Neovim$n"
    echo "  $c""nvim$n                  → open Neovim"
    echo "  :Lazy                   → LazyVim plugin manager (inside Neovim)"
    echo "  $c:Mason$n                → language tooling manager"
    echo "  $c:checkhealth$n          → Neovim diagnostics"
    echo ""

    echo "$y────────────────────────────────────────────────────────────$n"
    echo "$m""Tips:$n"
    echo "  List functions:  $b$c""functions | sort$n"
    echo "  List aliases:    alias"
    echo ""
end
