# Shared from Commanderx-code/Myfish: modules/fish/functions/lazyg.fish
# Generated by scripts/sync-myfish.py; edit Myfish instead.
function lazyg --description 'Stage, commit and push; stop on any error'
    if test (count $argv) -eq 0
        echo 'Usage: lazyg <message>' >&2
        return 1
    end
    gcom $argv; and git push
end
